name: Deploy to Azure

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          
         
      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./FileStorageService.sln

      # Build the solution
      - name: Build
        run: dotnet build ./FileStorageService.sln --configuration Release --no-restore

     # Run tests
      - name: Test
        run: dotnet test ./FileStorageService.sln --no-build --verbosity normal --configuration Release

      # Publish the application
      - name: Publish
        run: dotnet publish ./FileStorageService.sln -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'web-app-file-storage'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './publish'

      # # Optional: Verify deployment
      # - name: Check deployment
      #   run: curl -f https://your-app-name.azurewebsites.net/api/health
